import Head from 'next/head'
import useNumClick from '@/hooks/useNumClick'
export default function Home() {
  const { data: numClick } = useNumClick()
  console.log(numClick)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>Coucou</main>
    </>
  )
}
